### PR TITLE
Fix for: Failing tests /tests/core/tools/absoluterectposition

### LINKED ISSUE #2566: Failing tests /tests/core/tools/absoluterectposition
## Type of report

Failing tests

## Provide description of the task

Both tests from `/tests/core/tools/absoluterectposition` fails on iOS when run from dashboard. Works fine when tests are executed directly.

## Other details

* Browser: iOS
* CKEditor version: 4.11.0

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Fix for failing tests

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## What changes did you make?

Mocked `window.getScrollPosition` so test gives consistent results.

Closes #2566

### CODE REVIEW

File: tests/core/tools/absoluterectposition.js [hunk 1]
```diff
@@ -3,12 +3,23 @@
...
+		tests = {
 		setUp: function() {
+			var window = CKEDITOR.document.getWindow();
+
+			windowMock = sinon.stub( CKEDITOR.document, 'getWindow' );
+			windowMock.returns( window );
+
 			CKEDITOR.document.getBody().setStyle( 'height', '5000px' );
+
+			scrollPositionMock = sinon.stub( window, 'getScrollPosition' );
```
Comment (mlewand) [inline tests/core/tools/absoluterectposition.js]: You could simplify it by stubbing getScrollPosition directly in our window wrapper's prototype, like so:

> scrollPositionMock = sinon.stub( CKEDITOR.dom.window.prototype, 'getScrollPosition' );

File: tests/core/tools/absoluterectposition.js [hunk 2]
```diff
@@ -32,7 +43,7 @@
 
 			assertRect( absoluteRect, expected );
 
-			window.scrollBy( 0, 100 );
+			scrollPositionMock.returns( { x: 0, y: 100 } );
```
Comment (mlewand) [inline tests/core/tools/absoluterectposition.js]: Since you're explicitly setting the return value of a stub for each test case, I'd favor the entire mock creation to happen in the test case, and not in `setUp` method.

So you assign it like `scrollPositionMock = sinon.stub( window, 'getScrollPosition' ).returns( { x: 0, y: 100 } )`.

Restoring in `tearDown` is perfectly fine, but you'd have to adjust it for case if `scrollPosition` is `null` and also nullify it after it has been restored.

Reason for this is that someone adding a new test case won't be surprised by garbage `undefined` being returned by `getScrollPosition`.

File: tests/core/tools/absoluterectposition.js [hunk 3]
```diff
@@ -3,14 +3,20 @@
 ( function() {
 	'use strict';
 
-	var tests = {
+	var scrollPositionMock,
+		tests = {
 		setUp: function() {
```
[the remark this answers is not in the document]
Comment (mlewand) [reply tests/core/tools/absoluterectposition.js]: We can not make exception like that. We need to follow agreed code style. I have fixed that in 1d286993f.
