### PR TITLE
Fix error which appear with `columnDelete` command when table contained colspans

### LINKED ISSUE #577: Removing table columns throw an error
## Are you reporting a feature or a bug?

Bug

### Case 1
1. Open http://sdk.ckeditor.com/samples/table.html
2. Select whole 2013 section inside the table (see screenshot below)
3. Right click inside the selection and choose "Column"→"Delete Columns"

Example of selected columns

#### Expected result

Columns are deleted.

#### Actual result

Columns are not deleted and the error is thrown:

> ckeditor.js:66 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

### Case 2
1. Open http://sdk.ckeditor.com/samples/table.html
2. Select 2013 section without the header inside the table (see screenshot below)
3. Right click inside the selection and choose "Column"→"Delete Columns"

Example of selected columns

#### Expected result

Columns are deleted.

#### Actual result

Columns are deleted, but the error is thrown:

> ckeditor.js:66 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined

Additionally selection is put inside incorrect cell (see screenshot below).

Incorrect position of cursor

## Other details

* CKEditor version: 4.7.0

### PR DESCRIPTION
**Pull request by msamsel**
## What is the purpose of this pull request?
bug fix

## Does your PR contain necessary tests?
yes

### This PR contains
- [x] Unit tests
- [x] Manual tests

## What changes did you make?
- fix bug which forbid to delete columns when those were under colspans.
- fix bug where only last column was removed when colspan cell was selected.
- fix bug where cursor position might won't be returned, what generat the console error.
- add some brackets `{}` to if statements.

close #577

### CODE REVIEW

File: plugins/tabletools/plugin.js [hunk 1]
```diff
@@ -325,27 +330,34 @@
...
 
-		var firstRowCells = table.$.rows[ 0 ] && table.$.rows[ 0 ].cells;
-
 		// Where to put the cursor after columns been deleted?
 		// 1. Into next cell of the first row if any;
 		// 2. Into previous cell of the first row if any;
 		// 3. Into table's parent element;
-		var cursorPosition = new CKEDITOR.dom.element( firstRowCells[ startColIndex ] || ( startColIndex ? firstRowCells[ startColIndex - 1 ] : table.$.parentNode ) );
+		var cursorPosition;
+		if ( map[ 0 ].length - 1 > endColIndex && map[ 0 ][ endColIndex + 1 ].cellIndex !== -1 ) {
```
Comment (Comandeer) [inline plugins/tabletools/plugin.js]: Hmm… I don't get the logic behind this condition. It seems to work, but I don't understand why :D Could elaborate?

File: tests/plugins/tabletools/columndeletion.js [hunk 2]
```diff
@@ -0,0 +1,74 @@
+/* bender-tags: editor,unit */
```
Comment (Comandeer) [inline tests/plugins/tabletools/columndeletion.js]: Tests connected with `tableselection` plugin should be inserted into `tableselection/integrations` directory. It allows to easily find all issues related to integrations between `tableselection` and other plugins.

File: tests/plugins/tabletools/manual/columndeletionerror.md [hunk 3]
```diff
@@ -0,0 +1,14 @@
+@bender-tags: 4.7.2, bug, 577
```
Comment (Comandeer) [inline tests/plugins/tabletools/manual/columndeletionerror.md]: Tests connected with `tableselection` plugin should be inserted into `tableselection/integrations` directory. It allows to easily find all issues related to integrations between `tableselection` and other plugins.

File: tests/plugins/tabletools/manual/columndeletionerror.md [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea, toolbar, table, tabletools, tableselection, contextmenu, undo
+
+1. Open browser console.
+1. Select some cells somwhere under merged header.
+1. Selection should use `tableselection` plugin.
+1. Right click to open cntentxt menu.
```
Comment (Comandeer) [inline tests/plugins/tabletools/manual/columndeletionerror.md]: Please fix typos in test description.

File: tests/plugins/tabletools/columndeletion.js [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+		// #577
+		'test remove first column': function() {
+			// tests requires tableselection
+			if ( ( CKEDITOR.env.ie && CKEDITOR.env.version < 11 ) || bender.tools.env.mobile ) {
+				assert.ignore();
+			}
+			this.doTest( 'table-1', 'columnDelete' );
+		},
+
+		'test remove 2 last columns by single row selection': function() {
```
Comment (Comandeer) [inline tests/plugins/tabletools/columndeletion.js]: Please add ticket references before every test connected with it.

File: plugins/tabletools/plugin.js [hunk 6]
```diff
@@ -325,27 +330,34 @@
...
 		}
 
-		var firstRowCells = table.$.rows[ 0 ] && table.$.rows[ 0 ].cells;
-
 		// Where to put the cursor after columns been deleted?
 		// 1. Into next cell of the first row if any;
 		// 2. Into previous cell of the first row if any;
 		// 3. Into table's parent element;
-		var cursorPosition = new CKEDITOR.dom.element( firstRowCells[ startColIndex ] || ( startColIndex ? firstRowCells[ startColIndex - 1 ] : table.$.parentNode ) );
+		var cursorPosition;
```
Comment (Comandeer) [inline plugins/tabletools/plugin.js]: Actually I wonder if it could be moved to `tableselection` plugin using its internal `customizeTableCommand` function.

Comment (msamsel) [inline plugins/tabletools/plugin.js]: Generally `tabletools` doesn't depend on `tableselection` so we cannot assume that `tableselection` will be loaded.

File: plugins/tabletools/plugin.js (hunk 1 above)
Comment (msamsel) [inline plugins/tabletools/plugin.js]: First part of condition `map[ 0 ].length - 1 > endColIndex` check if there was some columns on the right after deleted part.
- `map[ 0 ].length - 1` is the last index of possible column value
- `endColIndex` is last index of deleted column.

Second part of condition `map[ 0 ][ endColIndex + 1 ].cellIndex !== -1` checks, if cell (`endColIndex + 1`) after deleted column, where we want to put cursor, is still in table. Theoretically it should be true, if first part is true ;)

File: tests/plugins/tabletools/columndeletion.js (hunk 2 above)
Comment (msamsel) [inline tests/plugins/tabletools/columndeletion.js]: I'll prepare two sets of test with and without tableselection plugin to cover more cases.

File: plugins/tabletools/plugin.js (hunk 1 above)
Comment (msamsel) [inline plugins/tabletools/plugin.js]: I removed second part it seems to be confusing.

File: tests/plugins/tabletools/manual/columndeletionerror.md (hunk 3 above)
Comment (msamsel) [inline tests/plugins/tabletools/manual/columndeletionerror.md]: it's done. ;)

**Comment by msamsel** [comment]
@Comandeer 
It's actually browser problem. I've report it to them:
- https://bugs.webkit.org/show_bug.cgi?id=175131
- https://bugs.chromium.org/p/chromium/issues/detail?id=752091

Browser natively, after opening context menu, highlight clicked word. In this case it cause enlarging selection to next cell if we're at the end of cell.

Do you think that I should prepare some custom solution to fix in CKEditor?

**Comment by Comandeer** [comment]
There are already some workarounds for context menu in our `tableselection` plugin, so it won't be any extraordinary situation. Such temporary workaround could be deleted when upstream issues will be fixed.

File: plugins/tabletools/plugin.js [hunk 7]
```diff
@@ -296,6 +296,47 @@
...
+					return selection;
+				}
+			}
+
+			range.setEndAt( previous, CKEDITOR.POSITION_BEFORE_END );
+			return range.select();
+		}
+
+		// Problem occures only on webkit in case of native selection (#577
+		if ( CKEDITOR.env.webkit && !selection.isFake && selection.getNative().type === 'Range' ) {
```
Comment (Comandeer) [inline plugins/tabletools/plugin.js]: Is the last part of the statement really needed? Probably it could be replaced with checking if range is non-collapsed.

File: plugins/tabletools/plugin.js [hunk 8]
```diff
@@ -296,6 +296,47 @@
...
+				if ( !previous ) {
+					return selection;
+				}
+			}
+
+			range.setEndAt( previous, CKEDITOR.POSITION_BEFORE_END );
+			return range.select();
+		}
+
+		// Problem occures only on webkit in case of native selection (#577
```
Comment (Comandeer) [inline plugins/tabletools/plugin.js]: It'll be nice to link also upstream issue here.

File: tests/plugins/tabletools/manual/columndeletionerror.md [hunk 9]
```diff
@@ -0,0 +1,24 @@
+@bender-tags: 4.7.2, bug, 577
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea, toolbar, table, tabletools, contextmenu, undo
+
+----
+1. Open browser console.
+1. Select some cells somewhere under merged header.
+1. Selection should use native selection.
+1. Right click to open context menu.
+1. Select Column -> Delete Column.
```
Comment (Comandeer) [inline tests/plugins/tabletools/manual/columndeletionerror.md]: It's "Delete Column**s**", not "~Column~".

**Comment by msamsel** [comment]
@Comandeer mentioned behaviour seems to be not related to this bug.
* You can reproduce your steps but instead of right-click use shortcut to open context menu `Shift + F10`. You will see that applying undo after that will restore proper collapsed selection.
* You can modify your steps and after opening context menu close it with ESC button. You will see that selection is extend to both cells even without using column delete.

Entire situation has happens because of using `right-click` not because of using `column delete`. And that's why such case should be fixed separately not in a scope of this task.
