### PR TITLE
Fixed: Failing initialize_hidden unit test

### LINKED ISSUE #2019: Failing initialize_hidden unit test
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.test:1030/tests/core/editor/initialize_hidden#tests%2Fcore%2Feditor%2Finitialize_hidden%20test%20auto%20initilization

### Expected result

Test passes.

### Actual result

Error is thrown:

> Timeout: wait() called but resume() never called.

## Other details

* Browser: Firefox Quantum 60.0.1
* CKEditor version: 4.5.0+

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Fixed failing test

## What changes did you make?

Due to race condition in Firefox bender added `instanceReady` listener with assertions after that event, so assertions were never fired. For that case I've added if statement which calls assertions right away if editor instance is ready.

Closes #2019

### CODE REVIEW

File: tests/core/editor/initialize_hidden.js [hunk 1]
```diff
@@ -5,26 +5,38 @@ CKEDITOR.replaceClass = 'ckeditor';
...
-					assert.areEqual( '<p>ed1</p>', bender.tools.compatHtml( evt.editor.getData() ) );
-				} );
-			}
-		} );
+		var editor = CKEDITOR.instances.editor1;
 
-		wait();
+		// For Firefox 60.0.1+ this code is executed after 'instanceReady' event so listener won't be called.
+		// For that case just assert it right away.
+		if ( editor.instanceReady ) {
```
Comment (msamsel) [inline tests/core/editor/initialize_hidden.js]: Using undocumented property might be a little bit risky. I think more appropriate will be using
`editor.status === 'ready'` instead.
https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#property-status
