### PR TITLE
Fix Travis CI

### LINKED ISSUE #2796: Fix Travis CI
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Look at travis results

### Expected result

Travis is working properly

### Actual result

Travis breaks during building

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

### PR DESCRIPTION
**Pull request by msamsel**
## What is the purpose of this pull request?

Bug

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## What changes did you make?

* Update travis config
* Add updated dependencies of bender, which are necessary for Travis
* Add new config variable `isTravis` to detect if current test is run on Travis
* Update paths in some test to be proper relative paths
* Ignore few tests, which fails on Travis
* Include new bender tools, which detects if tests are run on build version of CKEditor

## Additional info
Tests on Firefox tends to fail randomly, usually it's related to problem with `wait()` and `resume()` methods. There are sometimes issues with image tests, where some attributes are not refresh fast enough. It looks like firefox error, where some test cases checks assertion too fast or some other optimization happens. Resetting build job usually helps, but it tends to be a little annoying.
In really tough situation, there is possibility to debug travis job https://docs.travis-ci.com/user/running-build-in-debug-mode/#legacy-repositories.

Close #2796

### CODE REVIEW

File: tests/core/dom/range/getclientrects.js [hunk 1]
```diff
@@ -12,6 +12,16 @@
 			this.playground = doc.getById( 'playground' );
 		},
 
+		_should: {
+			ignore: {
+				// Tests randomly fails on FF in Travis
+				'test only element selection': bender.config.isTravis && CKEDITOR.env.gecko,
```
Comment (mlewand) [inline tests/core/dom/range/getclientrects.js]: You could actually extract `bender.config.isTravis && CKEDITOR.env.gecko` to a variable.

File: tests/_benderjs/ckeditor/static/tools.js [hunk 2]
```diff
@@ -91,6 +91,10 @@
 			return bender.tools.fixHtml( html, stripLineBreaks );
 		},
 
+		isBuild: function() {
```
Comment (mlewand) [inline tests/_benderjs/ckeditor/static/tools.js]: There is a much better namespace for this function: `bender.tools.env` namsepace. We should avoid throwing everything into `bender.tools` as we'd quickly have too much members there.

To better integrate with existing code over there, you can see that there are just properties. We don't expect build type (dev/build) to change between the tests, so it could be a property just like `bender.tools.env.mobile`.

File: tests/plugins/balloonpanel/_helpers/tools.js [hunk 3]
```diff
@@ -119,6 +119,23 @@ var balloonTestsTools = {
 				break;
 		}
 		return pos;
+	},
+
+	removeDottsFromUrl: function( expectedPath ) {
+		var parts = expectedPath.split( '/' ),
```
Comment (mlewand) [inline tests/plugins/balloonpanel/_helpers/tools.js]: The implementation would be much simpler if you'd use `CKEDITOR.tools.array.filter`.

File: tests/plugins/balloonpanel/cssloading.js [hunk 4]
```diff
@@ -17,13 +17,13 @@
...
 				// built version, such trick must be used (#1251).
-				'test loading css with path': CKEDITOR.revision !== '%REV%'
+				'test loading css with path': bender.tools.isBuild()
 			}
 		},
 
 		'test loading css with path': function() {
-			assert.areSame( 'kama,/apps/ckeditor/skins/kama/', CKEDITOR.skinName, 'config skinName should be with path' );
-			sinon.assert.calledWith( spy, balloonTestsTools.getDocumentOrigin() + '/apps/ckeditor/plugins/balloonpanel/skins/kama/balloonpanel.css' );
+			assert.areSame( 'kama,%BASE_PATH%../../apps/ckeditor/skins/kama/', CKEDITOR.skinName, 'config skinName should be with path' );
```
Comment (mlewand) [inline tests/plugins/balloonpanel/cssloading.js]: Please add a short note of explanation to why `removeDottsFromUrl` function is used, and add an issue reference ticket related to this PR.

File: tests/plugins/balloontoolbar/positioning.js [hunk 5]
```diff
@@ -92,8 +92,9 @@
 		},
 
 		'test panel - out of view - hcenter top': function( editor ) {
-			if ( editor.name == 'divarea' ) {
-				// divarea tests are failing, it's an upstream issue from balloonpanel (#1064).
+			if ( editor.name == 'divarea' || ( bender.config.isTravis && bender.tools.isBuild() ) ) {
+				// divarea tests are failing, it's an upstream issue from balloonpanel (#1064).ga
```
Comment (mlewand) [inline tests/plugins/balloontoolbar/positioning.js]:
```
// divarea tests are failing, it's an upstream issue from balloonpanel (#1064).ga
```

What is this "ga" doing here? 👮

File: tests/plugins/balloonpanel/_helpers/tools.js (hunk 3 above)
Comment (msamsel) [reply tests/plugins/balloonpanel/_helpers/tools.js]: I'm not sure if implementation would be simpler. Please notice that I need to remove also folder names in the path not only dots.
So when there is path like: `/one/two/three/../../four`, I need to receive `/one/four`. This is why I look on array from right to left and preserve information how many addtional folders have to be removed.
To achieve similar result I would need to revers array. Then have filter function in clouser, which will preserve information how many additoianl folders need to be removed. And then revers array again. I don't feel like using `CKEDITOR.tools.array.filter` will simplify thi for loop.

File: tests/plugins/balloontoolbar/positioning.js (hunk 5 above)
Comment (msamsel) [reply tests/plugins/balloontoolbar/positioning.js]: It's my shortcut from 'git add'. I probably write it here instead of terminal :(

**Comment by mlewand** [comment]
I'll just rebase it onto latest `master` branch.
