### PR TITLE
Fix for: Autolink throws an error in Source Mode

### LINKED ISSUE #2756: Autolink: TypeError: editor.getSelection(...) is null when typing in source view
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Enable AutoLink and Source Editing Area plugins
2. Goto source view
3. Start typing

### Expected result

Autolink must be disabled in source mode

### Actual result

These exceptions are thrown:
> TypeError: editor.getSelection(...) is null

on firefox
> TypeError: Cannot read property 'getRanges' of null

on chrome

In the line:
`var matched = CKEDITOR.plugins.textMatch.match( editor.getSelection().getRanges()[ 0 ], matchCallback );`

## Other details

* Browser: all
* CKEditor version: latest
* Installed CKEditor plugins: AutoLink and Source Editing Area

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [X] Unit tests
- [X] Manual tests

## What changes did you make?

Prevented on `key` listener in `sourcemode`.

Closes #2756

### CODE REVIEW

File: plugins/autolink/plugin.js [hunk 1]
```diff
@@ -41,7 +41,7 @@
 			editor.on( 'contentDom', function() {
```
Comment (mlewand) [inline plugins/autolink/plugin.js]: Technically this surrounding code is wrong, as it creates more than needed listeners. Every `contentDom` event (each time the editable is created) a new `editor#key` listener is added (on top of existing one).

`editor#key` don't need to wait for `contentDom` evt, so it's safe to remove it. Instead we redundant events being fired.

It's not the subject of this issue, but a minor thing that can be fixed along.

**Comment by mlewand** [comment]
Rebased onto latest `master` branch, resolved trivial conflict in the changelog file.
