### PR TITLE
Pasting image widget into table cell

### LINKED ISSUE #520: Widgets can not be properly pasted into a table cell
## Are you reporting a feature or a bug?

bug

https://codepen.io/anon/pen/PjWVZW (inline)
http://sdk.ckeditor.com/samples/captionedimage.html (replace)

reproduction steps 

1. copy image (crtl + c)
2. paste into a table cell
3. reapeat

### Expected result

properly pasted images which can be resized, selected and deleted with DEL / ctrl + x

### Actual result

images are missing the drag and drop handler + resize handler 
and alot of other unexpected behaviour like unable to write anything inside the table.

## Other details

* Browser: chrome
* OS: win 10
* CKEditor version: 4.7
* Installed CKEditor plugins: enhanced image plugin

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](http://docs.ckeditor.com/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](http://docs.ckeditor.com/#!/guide/dev_tests) and
[how to create tests](http://docs.ckeditor.com/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

* Now all non-table/mixed content is passed to other paste handlers and is no longer handled by table paste handler.
* Selecting cells after paste was moved to `afterPaste` handler.
* Logic of empting cells before real paste is also updated.
* However there is still one issue, which I don't have a good idea how to solve: after selecting more than one cell, pasting into them and clicking "Undo" button, only the first cell is selected. It's caused by the change introduced while passing mixed content to other paste handlers.

closes #520.

### CODE REVIEW

**Comment by Comandeer** [comment]
I've pushed fixes for failing tests (simple change from `paste` to `afterPaste` listener). I've also prepared additional test for testing paste flow when pasting non-tabular content.

File: plugins/tableselection/plugin.js [hunk 1]
```diff
@@ -536,32 +559,49 @@
...
+				getCellsBetween( new CKEDITOR.dom.element( pastedTableMap[ 0 ][ 0 ] ), cellToPaste ) :
+				selectedCells;
+
+			fakeSelectCells( editor, toSelect );
+		} );
 
 		// Handle mixed content (if the table is not the only child in the tmpContainer, we
 		// are probably dealing with mixed content). We handle also non-table content here.
+		// We just collapse selection to the first selected cell and pass non-table/mixed
+		// content to other paste handlers (#520).
```
Comment (Comandeer) [inline plugins/tableselection/plugin.js]: Actually this paste handler does not perform paste in such case. It just selects the first cell and ends its job – so I don't see my comment as outdated. Maybe it could be a little bit more detailed.

**Comment by Comandeer** [comment]
Ok, I've merged `t/520_fix` branch and newest `master`. I've also fixed failing tests in IE11.

**Comment by mlewand** [comment]
@f1ames please check whether your issues have been addressed.

**Comment by f1ames** [comment]
@mlewand should I merge it, or you will do the honors?

**Comment by f1ames** [comment]
Merging now :)

**Comment by mlewand** [comment]
Sry I was out, please do the honors 🙂

**Comment by mlewand** [comment]
Looks like this PR also fixed #460 🎉.
