### PR TITLE
Mentions plugin now matches diacritic characters

### LINKED ISSUE #2491: Mentions are not matching unicode/diacritic characters
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Use CKEDITOR 4.10 with mentions plugin
2. Include mentions data with accents like 'Céline TEST'
3. Try to use mentions with data typing '@Cé'

### Expected result

Mentions propose entry 'Céline TEST'

### Actual result

No results

## Other details

It seems due to emphasis/accents 
I've tried with direct data in array or with function feed.

I think we would have same results trying with accents or not (@Cel or @Cél must return same results).
It can be solved with a new regexp parameter to apply to request and data ?

Thanks per advance !

* Browser: Any
* CKEditor version: 4.10
* Installed CKEditor plugins: Mentions

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Bug

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

Fixed mentions regex to match diacritic characters.

Closes #2491

### CODE REVIEW

File: plugins/mentions/plugin.js [hunk 1]
```diff
@@ -142,7 +142,8 @@
 	};
 
 	function createPattern( marker, minChars ) {
-		var pattern = '\\' + marker + '\\w';
+		// Match also diacritic characters (#2491).
+		var pattern = '\\' + marker + '[_A-z0-9À-ž]';
```
Comment (mlewand) [inline plugins/mentions/plugin.js]: Let's be more precise with the regexp, your regexp catches also chars like `[`, `^`, backtick etc. `a-zA-Z` is the way to go here.

File: tests/plugins/mentions/manual/diacritic.md [hunk 2]
```diff
@@ -0,0 +1,16 @@
+@bender-tags: 4.11.0, 2491, bug, mentions
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea, toolbar, basicstyles, mentions
+
+1. Focus the editor.
```
Comment (mlewand) [inline tests/plugins/mentions/manual/diacritic.md]: Manual test should mention that you need to set up a Polish keyboard.

File: plugins/mentions/plugin.js (hunk 1 above)
Comment (mlewand) [reply plugins/mentions/plugin.js]: Please add a unit test ensuring that phrases with [^ are not matched.
