### PR TITLE
[Edge] Fixed: 'Permission denied' is thrown when opening panel instance

### LINKED ISSUE #2035: Edge Permission denied
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using Microsoft Edge, go to: https://ckeditor.com/latest/samples/index.html
2. Click any of the following buttons: Image, Spell Check, Style, Format, Size (and many others)
3. You will receive a Javascript Error: Permission denied

When running the samples on my website, there are no details for the error message (I'm not familiar with Edge though). But on the ckeditor.com samples page, there is a message that shows some more details. Here's the details after clicking the image button and receiving the permission denied error:

Could not locate https://ckeditor.com/latest/node_modules/cksource-samples-framework/components/grid/grid.less specified in source map

* Browser: Edge (Microsoft Edge 42.17134.1.0)
* OS: Window 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: Standard

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [X] Unit tests
- [X] Manual tests

## What changes did you make?

Edge throws 'permission denied' when trying to append an iframe with `src` attribute containing some javascript. This happens within `panel` plugin, excluded Edge from check, so `src` should be empty. After some testing it looks like nothing is broken.

Closes #2035

### CODE REVIEW

File: tests/plugins/panel/panel.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+			}
+
+			var editor = this.editor,
+				panel = new CKEDITOR.ui.panel( CKEDITOR.document, {
+					forceIFrame: true
+				} ),
+				html = panel.render( editor ),
+				src = html.match( /src="[^"]*"/i )[ 0 ];
+
+			src = src.substring( 5, src.length - 1 );
```
Comment (mlewand) [inline tests/plugins/panel/panel.js]: You could simplify it simply by using regexp group for `[^"]*` part in https://github.com/ckeditor/ckeditor-dev/blob/294ada7/tests/plugins/panel/panel.js#L21
