### PR TITLE
Edge 17 throws an error when pasting into editor

### LINKED ISSUE #2169: MS Edge 17 - paste image from another tab causes TypeError for isBlock
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using CKEditor build 4.9.2 in a React project in Microsoft Edge 17
2. Copy an image from another tab within Edge
3. Paste image into the CKEditor

### Expected result

No console error.

### Actual result

Console error: Unable to get property 'isBlock' of undefined or null reference

## Other details

* Browser: Microsoft Edge 17
* OS: Win10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: clipboard, dialog, specialchar

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Fixes

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests) and
[how to create tests](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [X] Manual tests

## What changes did you make?

Testing for custom mime types (just by trying setData with such type) makes dataTransfer inaccessible in Edge, so as a workaround for upstream issue I've added if statement which will omit such test on Edge.

Note:
I have different error in console, than described in original issue, but with my fix it looks to work fine.

Closes #2169.

### CODE REVIEW

File: plugins/clipboard/plugin.js [hunk 1]
```diff
@@ -2825,6 +2825,11 @@
 
 					fallbackDataTransfer._isCustomMimeTypeSupported = false;
 
+					// It looks like after our custom mime type test Edge 17 is denying access on nativeDataTransfer.
+					if ( CKEDITOR.env.edge && CKEDITOR.env.version > 16 ) {
+						return false;
```
[the remark this answers is not in the document]
Comment (engineering-this) [reply plugins/clipboard/plugin.js]: Oh, that negated return, good call. But now I am surprised that change actually makes it work.

**Comment by engineering-this** [comment]
I've tried such test for custom mime types on Edge:

```
var testTransfer = new DataTransfer();

testTransfer.setData( testType, testValue );
fallbackDataTransfer._isCustomMimeTypeSupported = testTransfer.getData( testType ) === testValue;
testTransfer.clearData( testType );
```

But such test still corrupts original data transfer, and Edge denies access to it's items. Also DataTransfer methods are poorly supported and it doesn't help in creating proper unit test.

File: CHANGES.md [hunk 2]
```diff
@@ -7,6 +7,10 @@ Fixed Issues:
 
 * [#2114](https://github.com/ckeditor/ckeditor-dev/issues/2114): [Autocomplete](https://ckeditor.com/cke4/addon/autocomplete) cannot be initialized before [`instanceReady`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#event-instanceReady).
 
+Fixed Issues:
```
Comment (Comandeer) [inline CHANGES.md]: There is already "Fixed Issues` section.

File: plugins/clipboard/plugin.js [hunk 3]
```diff
@@ -2825,6 +2825,12 @@
 
 					fallbackDataTransfer._isCustomMimeTypeSupported = false;
 
+					// It looks like after our custom mime type test Edge 17 is denying access on nativeDataTransfer (#2169).
+					// Upstream issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18089287/
+					if ( CKEDITOR.env.edge && CKEDITOR.env.version > 16 ) {
```
Comment (Comandeer) [inline plugins/clipboard/plugin.js]: `CKEDITOR.env.version` is a float, not integer. In this case this conditional is targeting also 16.x Edge.
