### PR TITLE
Fixed expandable button label when clicked

### LINKED ISSUE #421: MenuButton with label puts "(Selected)" at the end of the label when clicked
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/14237

## Provide detailed reproduction steps (if any)

1. Add a Menu Button to the toolbar, using the menubutton plugin.
2. Change the skin css to show the label for the button.
3. Open the editor and click on the menu button

### Expected result

The menu button label should not change.

### Actual result

The menu button label changes from 'Label' to 'Label (Selected)'.

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

Removed invalid label from an expandable button and added `aria-expanded` attribute for accessibility.
I also removed unused language files and property.

Closes #421

### CODE REVIEW

File: plugins/button/plugin.js [hunk 1]
```diff
@@ -331,19 +328,22 @@
 			if ( element ) {
 				element.setState( state, 'cke_button' );
 
-				state == CKEDITOR.TRISTATE_DISABLED ?
-					element.setAttribute( 'aria-disabled', true ) :
+				if ( state == CKEDITOR.TRISTATE_DISABLED ) {
```
Comment (Comandeer) [inline plugins/button/plugin.js]: In fact it could be even simplified to switching true/false value for the attribute. There is no need to remove it.

This is the case for all true/false ARIA attributes.

File: plugins/button/plugin.js [hunk 2]
```diff
@@ -331,19 +328,22 @@
...
+						element.setAttribute( 'aria-pressed', true );
+					} else {
 						element.removeAttribute( 'aria-pressed' );
+					}
 				} else {
-					var newLabel = state == CKEDITOR.TRISTATE_ON ?
-						this._.editor.lang.button.selectedLabel.replace( /%1/g, this.label ) : this.label;
-					CKEDITOR.document.getById( this._.id + '_label' ).setText( newLabel );
+					element.setAttribute( 'aria-expanded', state == CKEDITOR.TRISTATE_ON );
+					CKEDITOR.document.getById( this._.id + '_label' ).setText( this.label );
```
Comment (Comandeer) [inline plugins/button/plugin.js]: Is there a need to update label?

File: tests/plugins/button/manual/label.md [hunk 3]
```diff
@@ -0,0 +1,15 @@
+@bender-tags: 4.10.2, 421, bug, editor, button
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea, toolbar, language
+
+Click `Language` button.
```
Comment (Comandeer) [inline tests/plugins/button/manual/label.md]: There should be additional steps for testing in screen reader.

File: plugins/button/plugin.js (hunk 2 above)
Comment (jacekbogdanski) [reply plugins/button/plugin.js]: Nope :+1:

File: plugins/button/plugin.js [hunk 4]
```diff
@@ -330,20 +327,14 @@
...
-					element.setAttribute( 'aria-disabled', true ) :
-					element.removeAttribute( 'aria-disabled' );
+				element.setAttribute( 'aria-disabled', state == CKEDITOR.TRISTATE_DISABLED );
 
 				if ( !this.hasArrow ) {
 					// Note: aria-pressed attribute should not be added to menuButton instances. (https://dev.ckeditor.com/ticket/11331)
-					state == CKEDITOR.TRISTATE_ON ?
-						element.setAttribute( 'aria-pressed', true ) :
-						element.removeAttribute( 'aria-pressed' );
+					element.setAttribute( 'aria-pressed', state == CKEDITOR.TRISTATE_ON );
```
[the remark this answers is not in the document]
Comment (Comandeer) [reply plugins/button/plugin.js]: See also #2444.

File: tests/plugins/button/manual/label.html [hunk 5]
```diff
@@ -0,0 +1,27 @@
+<span id="results"></span>
+<div id="editor"></div>
+
+<script>
+	var results = CKEDITOR.document.getById( 'results' ),
+		editor = CKEDITOR.replace( 'editor', {
```
Comment (Comandeer) [inline tests/plugins/button/manual/label.html]: In such test editor's language should be forced, as in my editor there is no "Set language" button, but "Ustaw język" one ;)

File: tests/plugins/button/manual/label.html [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+			language: 'en',
+			on: {
+				instanceReady: function() {
+					var toolbox = editor.ui.space( 'toolbox' ),
+						langBtn = toolbox.findOne( '.cke_button' );
+
+					updateResults();
+
+					langBtn.on( 'click', updateResults );
```
Comment (Comandeer) [inline tests/plugins/button/manual/label.html]: Clicking the button does not cover all cases:

* closing menu in any way (clicking elsewhere, selecting any option, pressing <kbd>Esc</kbd>…),
* opening menu via keyboard (kinda weird, because at least <kbd>Enter</kbd> should generate `click` event on link 🤔; yet there is always <kbd>Space</kbd>).

Not sure, but probably polling the value is the most bulletproof solution.

File: tests/plugins/button/manual/label.md [hunk 7]
```diff
@@ -0,0 +1,33 @@
...
+## Screen reader
+
+**Note**: you need to enable screen reader for this test.
+
+1. Click `Language` button.
+1. Blur `Language` button by clicking outside of the editor.
+
+### Expected
+
+* When menu is opened, screen reader reads "menu".
```
Comment (Comandeer) [inline tests/plugins/button/manual/label.md]: In fact screen reader should read "expanded". "menu" is an announcement of opened menu, not the fact that the button was clicked.

File: tests/plugins/button/manual/label.md [hunk 8]
```diff
@@ -0,0 +1,33 @@
...
+### Unexpected
+
+* **aria-expanded:** null
+* **label:** Set language (Selected)
+
+## Screen reader
+
+**Note**: you need to enable screen reader for this test.
+
+1. Click `Language` button.
```
Comment (mlewand) [inline tests/plugins/button/manual/label.md]: As for screen reader tests, please use keyboard instead. This is a more common way to use computer for users with screen readers.

Comment (Comandeer) [reply tests/plugins/button/manual/label.md]: It was so obvious to me that I just understood this step as "click with <kbd>Space</kbd>/<kbd>Enter</kbd> key"…
