### PR TITLE
T/501 Allow opening dialog for an empty anchor

### LINKED ISSUE #501: Double click does not open dialog for anchors
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open http://sdk.ckeditor.com/samples/classic.html
2. Insert empty anchor inside the editor.
3. Double click newly inserted anchor.

### Expected result

Dialog allowing to edit the anchor is opened.

### Actual result

Nothing happens.

## Other details

* CKEditor version: 4.7.0

This issue depends on #476 and seems to be connected with the fix for http://dev.ckeditor.com/ticket/11956

### PR DESCRIPTION
**Pull request by beatadelura**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

Yes

### This PR contains

- [X] Unit tests
- [X] Manual tests

## What changes did you make?

Add a new condition to element variable on double-click.

Closes #501

### CODE REVIEW

File: plugins/link/plugin.js [hunk 1]
```diff
@@ -94,10 +94,11 @@
 			editor.on( 'doubleclick', function( evt ) {
 				// If the link has descendants and the last part of it is also a part of a word partially
 				// unlinked, clicked element may be a descendant of the link, not the link itself. (http://dev.ckeditor.com/ticket/11956)
-				var element = CKEDITOR.plugins.link.getSelectedLink( editor ) || evt.data.element.getAscendant( 'a', 1 );
+				// evt.data.element condition allows opening anchor dialog if the anchor is empty (#501).
+				var element = CKEDITOR.plugins.link.getSelectedLink( editor ) || evt.data.element.getAscendant( 'a', 1 ) || evt.data.element;
```
Comment (Comandeer) [inline plugins/link/plugin.js]: I wonder if this condition could be simplified, e.g. setting `element` only if `evt.data.element` is `a` or `img`.

File: plugins/link/plugin.js [hunk 2]
```diff
@@ -94,10 +94,11 @@
...
 
-				if ( element && !element.isReadOnly() ) {
-					if ( element.is( 'a' ) ) {
+				if ( element ) {
+					if ( element.is( 'a' ) && !element.isReadOnly() ) {
```
Comment (Comandeer) [inline plugins/link/plugin.js]: Why this condition is moved here?

File: tests/plugins/link/manual/anchordialog.md [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+
+1. Double-click on anchor.
+
+**Expected result:**
+
+Anchor dialog has been opened.
+
+**Unexpected result:**
+
+Nothing happend.
```
Comment (Comandeer) [inline tests/plugins/link/manual/anchordialog.md]: Typo ;)

Comment (beatadelura) [inline tests/plugins/link/manual/anchordialog.md]: Changed 👍

File: plugins/link/plugin.js (hunk 2 above)
Comment (beatadelura) [inline plugins/link/plugin.js]: This is a remnant of the experiments. I moved it to the right place :)

File: plugins/link/plugin.js (hunk 1 above)
Comment (beatadelura) [inline plugins/link/plugin.js]: @Comandeer PTAL 👀

File: tests/plugins/link/anchor.js [hunk 4]
```diff
@@ -26,6 +26,31 @@
...
+
+			bot.setData( '<p><a name="foo" id="foo"></a></p>', function() {
+
+				var range = new CKEDITOR.dom.range( editor.document );
+				range.selectNodeContents( editor.editable().findOne( '[data-cke-real-element-type=anchor]' ) );
+				range.select();
+
+				editor.on( 'dialogShow', function( evt ) {
+					resume( function() {
+						assert.areSame( evt.data._.name, 'anchor' );
```
Comment (f1ames) [inline tests/plugins/link/anchor.js]: You can pass 3rd parameter as an assert description. In this case it could be useful because it might not be clear at the first glance what this assert is checking. It could look something like:
`assert.areSame( evt.data._.name, 'anchor', 'Anchor dialog has been opened.' )`

**Comment by f1ames** [comment]
@Comandeer, please check if all your requests were resolved.

File: plugins/link/plugin.js [hunk 5]
```diff
@@ -93,8 +93,9 @@
 
 			editor.on( 'doubleclick', function( evt ) {
 				// If the link has descendants and the last part of it is also a part of a word partially
-				// unlinked, clicked element may be a descendant of the link, not the link itself. (http://dev.ckeditor.com/ticket/11956)
-				var element = CKEDITOR.plugins.link.getSelectedLink( editor ) || evt.data.element.getAscendant( 'a', 1 );
+				// unlinked, clicked element may be a descendant of the link, not the link itself (http://dev.ckeditor.com/ticket/11956).
+				// The evt.data.element.getAscendant( 'img', 1 ) condition allows opening anchor dialog if the anchor is empty (#501).
+				var element = evt.data.element.getAscendant( 'a', 1 ) || evt.data.element.getAscendant( 'img', 1 );
```
Comment (Comandeer) [inline plugins/link/plugin.js]: Couldn't it be further simplified to:
```javascript
evt.data.element.getAscendant( { a: 1, img: 1 }, true );
```
?

Comment (beatadelura) [inline plugins/link/plugin.js]: True, it looks better this way :) Changed 👍  PTAL @Comandeer
