### PR TITLE
Ignore one XSS test on Chrome Linux

### LINKED ISSUE #431: Unit tests fails in Chrome on Travis CI in CKEditor dev version
# Are you reporting a feature or a bug?

Other: Integration issue -  it is an issue connected with Travis CI, not sure if the cause is in the code base.

## Provide detailed reproduction steps (if any)

See https://travis-ci.org/ckeditor/ckeditor-dev/jobs/236308123. Seems like Chrome loses focus when running unit tests (tests connected with focus are failing). Strangely it happens only with dev version, built tests run passes.

## Other details

* Browser: Chrome 58 run on Xvfb
* OS: Linux
* CKEditor version: latest `master` dev version (https://github.com/ckeditor/ckeditor-dev/commit/c5676c7b80f25254710636308694c879e6f05f18)
* Installed CKEditor plugins: …

### PR DESCRIPTION
**Pull request by f1ames**
## What is the purpose of this pull request?

Other: unit test fix.

## What changes did you make?

See #431 for details (https://github.com/ckeditor/ckeditor-dev/issues/431#issuecomment-305422790).

Closes #431.

### CODE REVIEW

File: tests/core/htmldataprocessor.js [hunk 1]
```diff
@@ -1326,10 +1326,11 @@
 		// Only WebKit removes preceding spaces in the attribute.
 		'<p><iframe src="' + ( CKEDITOR.env.webkit ? '' : '   ' ) + 'javascript:window.parent.%xss%;"></iframe></p>' ); // jshint ignore:line
 
-	// The `src="&#10;&#106;javascript:..."` is treated as some different protocol in Edge/IE8.
+	// The `src="&#10;&#106;javascript:..."` is treated as some different protocol in Edge/IE8 and also Chrome on Linux.
 	// IE8 treats it as an URL and opens it which reloads the whole page.
 	// While on Edge the tests passes, the browser prompts with "open as" dialog.
-	if ( !( CKEDITOR.env.ie && CKEDITOR.env.version == 8 || CKEDITOR.env.edge ) ) {
+	// On Chrome Linux it prompts `Open xdg-open?` dialog, which gains focus so other tests requiring focus fails.
+	if ( !( CKEDITOR.env.ie && CKEDITOR.env.version == 8 || CKEDITOR.env.edge || CKEDITOR.env.chrome && bender.tools.env.linux ) ) {
```
Comment (mlewand) [inline tests/core/htmldataprocessor.js]: Can we transform it into:
`if ( !( CKEDITOR.env.ie && CKEDITOR.env.version == 8 || CKEDITOR.env.edge ) && !( CKEDITOR.env.chrome && bender.tools.env.linux ) ) {`
? So that it is in two groups, I feel like this version will be more readable.

**Comment by mlewand** [comment]
LGTM!
