### PR TITLE
Tableresize plugin should check if table body exists.

### LINKED ISSUE #417: Tableresize throws an error when hovering over table with only header rows
## What type of issue would you like to report?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/17066

## Provide detailed reproduction steps (if any)

1. Set editor config to:
```
config.plugins =
	'table,' +
	'tableresize,' +
	'tableselection,' +
	'toolbar,' +
	'wysiwygarea';
```
2. Set editor content to:
```
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<thead>
	<tr>
		<th scope="col">1</th>
		<th scope="col">2</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<td>3</td>
		<td>4</td>
	</tr>
	</tbody>
</table>

<p>Foobar</p>
```
3. Switch to WYSIWYG mode.
1. Select part of the table (including header) and copy.
1. Paste somewhere else.
1. Hover over pasted table.

### Expected result

It is possible to resize a table (especially column by dragging inner border). No exception is thrown.

### Actual result

Exception is thrown. It is not possible to resize the table.

## Other details

* Browser: Chrome, FF, IE
* OS: OS X
* CKEditor version: 4.7.0
* Installed CKEditor plugins: _See step 1 in repro steps_

### PR DESCRIPTION
**Pull request by f1ames**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](http://docs.ckeditor.com/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](http://docs.ckeditor.com/#!/guide/dev_tests) and
[how to create tests](http://docs.ckeditor.com/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

Closes #417.

### CODE REVIEW

**Comment by f1ames** [comment]
@Comandeer Do you mean table with only `tfoot` element? I think it is reasonable to include it here too.

File: plugins/tableresize/plugin.js [hunk 1]
```diff
@@ -70,7 +74,12 @@
 		}
 
 		if ( table.$.tFoot ) {
-			pillarHeight += table.$.tFoot.offsetHeight;
+			var tFoot = new CKEDITOR.dom.element( table.$.tFoot );
```
Comment (Comandeer) [inline plugins/tableresize/plugin.js]: After that changes we have very similar code in three parts of this plugin. It will be nice to extract it into separate function.

File: tests/plugins/tableresize/manual/footeronly.md [hunk 2]
```diff
@@ -0,0 +1,12 @@
+@bender-ui: collapsed
+@bender-tags: tc, 4.7.1, gh417
```
Comment (Comandeer) [inline tests/plugins/tableresize/manual/footeronly.md]: Please change tags to our new convention.

File: tests/plugins/tableresize/manual/headeronly.md [hunk 3]
```diff
@@ -0,0 +1,12 @@
+@bender-ui: collapsed
+@bender-tags: tc, 4.7.1, gh417
```
Comment (Comandeer) [inline tests/plugins/tableresize/manual/headeronly.md]: Please change tags to our new convention.

**Comment by f1ames** [comment]
Rebased on latest `master`.
