### PR TITLE
Use XHR as possible uploading mechanism in filebrowser plugin

### LINKED ISSUE #643: File browser plugin should allow for setting custom HTTP headers
## Are you reporting a feature or a bug?

Feature

## Check if the issue is already reported

* https://dev.ckeditor.com/ticket/13791
* https://github.com/cksource/ckfinder-connector-php/issues/245#issuecomment-296366359

## Provide detailed reproduction steps (if any)

[Uploading dropped files](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_file_upload-section-editor-side-configuration) allows for creating cross-origin AJAX requests by adding custom HTTP requests.

Unfortunately this is not possible in the [File Browser](https://ckeditor.com/cke4/addon/filebrowser) plugin.

This is caused by the File Browser plugin currently using a standard `<form>` element that is submitted upon clicking the "Send it to the Server" button.

Mouse cursor over the "Send it to the Server" button

## Solution

We'll implement an **additional upload method** for the File Browser plugin that uses `XMLHttpRequest` through the [File Tools](https://ckeditor.com/cke4/addon/filetools) plugin.

The new upload method could be enabled using the `config.filebrowserUploadMethod` property.

The old method using the plain `<form>` element will still be supported as it is required by old browsers.

For 4.8.x, the `<form>`element will still be used by default since we cannot make backward incompatible changes in a minor release. Early adopters will already be able to enable it by setting:

```js
config.filebrowserUploadMethod = 'xhr';
```

The default behavior will be changed in version 4.9.0 (#1365).

## Browser Compatibility

All [officially supported browsers](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_browsers) except Internet Explorer 8 and 9.

The new feature will not be compatible with IE8 and IE9 as there is no Form Data type available there. These browsers will, however, gracefully fall back to the old `<form>`-based solution. As a result no custom headers will be sent, but the editor will still attempt to upload the file.

## Other details

As stated in ticket https://dev.ckeditor.com/ticket/13791, it will probably be easier  to create a new plugin then redesign the existing one.

* Browser: Any
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: `filebrowser`

### PR DESCRIPTION
**Pull request by msamsel**
## What is the purpose of this pull request?

New feature

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests) and
[how to create tests](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

- change way how filebrowser upload files - prefer using XHR
- allow on providing custom headers to XHR used when files are uploaded
- add config flag which will force to use `form submit` behaviour when files are uploaded

Closes #643.

### CODE REVIEW

File: plugins/filetools/plugin.js [hunk 1]
```diff
@@ -885,3 +911,16 @@
...
+/**
+ * Additional headers of XMLHttpRequest used during file upload with plugins: {@link CKEDITOR.fileTools} and filebrowser.
+ *
+ * 	config.xmlHttpRequestHeaders = {
+ * 		'Cache-Control': 'no-cache',
+ * 		'X-CUSTOM': 'HEADER'
+ * 	};
+ *
+ * @since 4.8.1
+ * @cfg {Object} [xmlHttpRequestHeaders=null]
```
Comment (mlewand) [inline plugins/filetools/plugin.js]: This config property should be prefixed with `fileTools_` just like the other filetools config property.

**Comment by mlewand** [comment]
I'll take over this one from here.
