### PR TITLE
Changing list type wont throw error for empty list elements

### LINKED ISSUE #2411: Pasting empty nested list and converting it to different list type throws error
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://sdk.ckeditor.com/samples/fullpreset.html.
2. Clear Editor contents and switch to source mode.
3. Paste below HTML
```
<ul>	
	<li>
	<div>test
	<ul>
	</ul>
	</div>
	</li>
	<li>test</li>
</ul>
```
In Chrome it is enough to use 

```
<ul>	
	<li>
	<div>test
	<ul>
	</ul>
	</div>
	</li>
</ul>
```
4. Switch to wysiwyg mode
5. Press `Ctrl+A` na dclick on Numbered  List button

### Expected result

No error gets thrown.

Perhaps as an alternative solution such list should be filtered by ACF.

### Actual result

JavaScript error gets thrown: 
**Message:** Cannot read property 'parent' of undefined
**Line:** 319
**URI:** `/ckeditor-dev/plugins/list/plugin.js
`
## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: List

----
The Original scenario was:
1. Open https://codepen.io/pratikgolchha/pen/wxGbRd in Edge
2. Copy everything form https://docs.microsoft.com/zh-cn/powerapps/maker/canvas-apps/controls/control-gallery and paste in the CKEditor
3. Select all contents and apply bulleted list and then numbered list
4. Check the console

This document is huge so maybe there is something extra what is causing the same issue (there shouldn't be but it may).

### PR DESCRIPTION
**Pull request by msamsel**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

* Fix throwing errors in console, when markup with empty `ul` list was changed to different list type.

Close #2411

Related also to #2438

### CODE REVIEW

File: tests/plugins/list/blockconversion.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+	},
+	inline: {
+		name: 'inline',
+		creator: 'inline'
+	}
+};
+
+var tests = {
+	'test conversion of embedded unordered list and paragraphs to numbered list': function( editor, bot ) { // Strange test result for: 0, 8
+		var testesLength = 9;
```
Comment (mlewand) [inline tests/plugins/list/blockconversion.js]: Subsequent `var` declarations/initialization should be contained within a single `var` statement.

Comment (mlewand) [reply tests/plugins/list/blockconversion.js]: This issue appears later on, please correct each occurence.

File: tests/plugins/list/blockconversion.html [hunk 2]
```diff
@@ -0,0 +1,468 @@
+<!--
+
+Strange output markup for tests:
```
Comment (mlewand) [inline tests/plugins/list/blockconversion.html]: Avoid information duplication. You have already provided this info in `blockconversion.js`. 

`blockconversion.js` is where the logic of tests are so it is the best place to put this information. Here it's not needed, as it is only a _resource_ file for the logic.

File: tests/plugins/list/blockconversion.js [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+		}
+	},
+	inline: {
+		name: 'inline',
+		creator: 'inline'
+	}
+};
+
+var tests = {
+	'test conversion of embedded unordered list and paragraphs to numbered list': function( editor, bot ) { // Strange test result for: 0, 8
```
Comment (mlewand) [inline tests/plugins/list/blockconversion.js]: `Strange test result for: 0, 8` comment will look much better in a line below. Here it exceeds 120 chars which, if convenient, we like to avoid.

File: core/tools.js [hunk 4]
```diff
@@ -1569,6 +1569,19 @@
...
 		},
 
+		/**
+		 * Counts childes of given {@link CKEDITOR.dom.element} omitting {@link CKEDITOR.dom.comment}.
+		 *
+		 * @since 4.11.2
+		 * @param {CKEDITOR.dom.element} node Element whos children will be counted.
+		 * @returns {Number} Amount of node's children without counting comments.
+		 */
+		childCountWithoutComments: function( node ) {
```
Comment (mlewand) [inline core/tools.js]: We can't add a method like that, it doesn't belong here.

1. Logically it belongs to `CKEDITOR.dom.element` type - this is where it should be added.
1. It's too specific to your particular use case. Having a method like that would be excuse for getChildCountWithoutNodes, getChildCountWithoutElements etc. Instead [`getChildCount` method](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_element.html#method-getChildCount) should be modified to accept `options` param, that allows to specify `options.exclude` or `options.include`. So you'd call it like `elem.getChildCount( { exclude: [ CKEDITOR.NODE_COMMENT ] } );`.
1. Name is not aligned with existing [`getChildCount` method](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_element.html#method-getChildCount).

Finally there's a minor naming issue, `node` can not have children so the arg should be called `element` just like you described in `@param`'s description.

I should have pointed this out in previous review.

**Comment by mlewand** [comment]
I have fixed the issue that I raised during the review by simply inlining the function. Ideally I'd like CKEDITOR.dom.element methods to get `include` / `exclude` options, but that would mean that this fix would need to wait for the major release.
