### PR TITLE
Fix for `range.extractContents` to work like `cloneContents`

### LINKED ISSUE #644: extractContents returns incorrect result when multiple nodes are selected
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

https://dev.ckeditor.com/ticket/14256

## Provide detailed reproduction steps (if any)

Please try this codepen: https://codepen.io/anon/pen/MoZOPE

1. Clear editor contents and type "This is some sample text"
2. "This is some [sample text]" - apply marker yellow to given selection
3. "This is [some sample text]" - apply bold to given selection
4. "[This is some sample text]" - apply below code in browser console to given selection

```
var currentRange = CKEDITOR.instances.editor1.getSelection().getRanges()[0];
console.log(currentRange.extractContents().getHtml());
```
### Expected result

`This is <strong>some <span class="marker">sample text</span></strong> `

### Actual result
`This is <strong><span class="marker">sample text</span>some </strong>`

## Other details

* Browser: Any
* OS: Any
* CKEditor version: CKEditor 4.5.0+
* Installed CKEditor plugins: N/A

### PR DESCRIPTION
**Pull request by msamsel**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

yes

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?
- pass flag `toStart` to append method in extract mode
- fix test which was wrongly design and accept previously wrong code

close #644

### CODE REVIEW

File: tests/core/dom/range/extractcontents.js [hunk 1]
```diff
@@ -379,6 +379,38 @@
 
 			// See: execContentsAction in range.js.
 			assert.isInnerHtmlMatching( '<p>Foo bar</p>', docFrag.getHtml(), 'Extracted HTML' );
+		},
+
+		// #644
+		'test extract nested tags': function() {
+			bender.editorBot.create( {
```
Comment (mlewand) [inline tests/core/dom/range/extractcontents.js]: I don't think there's a need to create a dedicated editor here.

Instead move `<p>111<strong>222<span>333<em>444</em></span>555<sup>666</sup>777<sub>888</sub></strong></p>` fixture to the `.html` file and use it here (with a proper selection).

File: tests/core/dom/range/manual/extractcontentsreturnproperstructure.md [hunk 2]
```diff
@@ -0,0 +1,11 @@
+@bender-tags: 4.7.2, bug, 644, range
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea, toolbar, basicstyles, stylescombo, sourcearea, notification
+
+1. Select all text in editor.
+1. Press button bellow.
+1. There should appear 2 belowe button, and selected text should be removed from editor.
```
Comment (mlewand) [inline tests/core/dom/range/manual/extractcontentsreturnproperstructure.md]: There should appear 2 of what? You did not specify.

Comment (mlewand) [inline tests/core/dom/range/manual/extractcontentsreturnproperstructure.md]: Typo in "belowe".

File: tests/core/dom/range/extractcontents.js [hunk 3]
```diff
@@ -379,6 +381,35 @@
...
+			docFrag = range.extractContents();
+
+			assert.isInnerHtmlMatching( '111<strong>222<span>333<em>444</em></span>555<sup>666</sup>777<sub id="_sub">888</sub></strong>', docFrag.getHtml() );
+
+		},
+
+		// #644
+		'test extractContents and cloneContents provides equal results': function() {
+			var range = new CKEDITOR.dom.range( doc ),
+				extractFrag, cloneFrag;
```
Comment (mlewand) [inline tests/core/dom/range/extractcontents.js]: Code style: variables should be defined in separate lines.

File: tests/core/dom/range/extractcontents.js [hunk 4]
```diff
@@ -379,6 +381,35 @@
...
+
+			range.setStart( doc.getById( '_pe' ).getFirst(), 0 );
+			range.setEnd( doc.getById( '_sub' ).getFirst(), 3 );
+
+			cloneFrag = range.cloneContents(),
+			extractFrag = range.extractContents();
+
+			assert.isInnerHtmlMatching( bender.tools.fixHtml( cloneFrag.getHtml() ), bender.tools.fixHtml( extractFrag.getHtml() ) );
```
Comment (mlewand) [inline tests/core/dom/range/extractcontents.js]: This line got long and ugly. Rather than using `assert.beautified.html` multiple times, how about assert using beautified HTML?

`assert.beautified.html( cloneFrag.getHtml(), extractFrag.getHtml() );`
