### PR TITLE
T/566

### LINKED ISSUE #566: CKEditor Changes Table Style and Border
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Not Found

## Provide detailed reproduction steps (if any)

1. Go to http://sdk.ckeditor.com/samples/standardpreset.html
2. Edit &lt;table&gt; tag in "Source" view - edit to resemble the below:

    &lt;table align="right" border="0" cellpadding="5" cellspacing="0" style="border: 0px solid #000000;"&gt;

3. Switch to WYSIWYG view; it has a border.
4. Switch back to code view: It is now:

    &lt;table align="right" border="1" cellpadding="5" cellspacing="0"&gt;

### Expected result

It shouldn't put any border, since no border is requested.

### Actual result

It thinks a border was requested and sets border="1"

## Other details

* Browser: Chrome 59 @ Linux, Mac, Windows; Edge
* OS: Linux, Mac, Windows
* Installed CKEditor plugins: standard presets

## Comments

First time bug-poster, long-time user!

Behavior is the same in the nightly build standard editor.

This can be worked-around by breaking the border: tag apart into border-color, border-style, and border-width, which then doesn't change the border attribute.

### PR DESCRIPTION
**Pull request by wojtekw92**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](http://docs.ckeditor.com/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](http://docs.ckeditor.com/#!/guide/dev_tests) and
[how to create tests](http://docs.ckeditor.com/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [X] Unit tests
- [X] Manual tests

## What changes did you make?

closes #566
should be merged after #616 and rebase

### CODE REVIEW

File: plugins/table/plugin.js [hunk 1]
```diff
@@ -30,8 +30,12 @@ CKEDITOR.plugins.add( 'table', {
 					element: 'table',
 					right: function( element ) {
 						if ( element.styles ) {
-							if ( element.styles.border && element.styles.border.match( /solid/ ) ) {
-								element.attributes.border = 1;
+							if ( element.styles.border ) {
+								var parsedStyle = CKEDITOR.tools.style.parse.border( element.styles.border );
+								if ( parsedStyle.style && parsedStyle.style === 'solid' &&
```
Comment (f1ames) [inline plugins/table/plugin.js]: Shouldn't it check for other border styles (all but `none` and `hidden`)?

File: core/tools.js [hunk 2]
```diff
@@ -1627,6 +1627,21 @@
...
+					'dashed',
+					'solid',
+					'double',
+					'groove',
+					'ridge',
+					'inset',
+					'outset'
+				],
+
+				_widthRegExp: /^(thin|medium|thick|[\+-]?\d+\.?\d*\S*)$/,
```
Comment (f1ames) [inline core/tools.js]: Well, the `[\+-]?\d+\.?\d*\S*` regex works same as `[\+-]?\d+\S*` because `.?` and `\d*` are optional (zero or more occurrences) and `\S*` group already contains them.

It will also match e.g. `12. ` which is invalid value (https://developer.mozilla.org/en-US/docs/Web/CSS/number).

> A length consists of a &lt;number&gt; followed by a unit (px, em, pc, in, mm, …). As with all CSS dimensions, there is no space between the unit literal and the number. The length unit is optional after the number 0.

So for all non `0` values unit is not optional.

I think this regexp should be tweaked to match values more precisely.

File: core/tools.js [hunk 3]
```diff
@@ -1713,6 +1728,50 @@
...
+						if ( !ret.color ) {
+							var parseColor = CKEDITOR.tools.style.parse._findColor( val );
+							if ( parseColor.length ) {
+								ret.color = parseColor[ 0 ];
+								return;
+							}
+						}
+
+						if ( !ret.style ) {
+							if (  CKEDITOR.tools.indexOf( CKEDITOR.tools.style.parse._borderStyle, val ) !== -1 ) {
```
Comment (f1ames) [inline core/tools.js]: Double space in `if (  CKE...`.

File: tests/core/tools/style.js [hunk 4]
```diff
@@ -128,6 +128,34 @@
...
+
+		'test style.parse.border with mixed color and style': function() {
+			objectAssert.areEqual( { color: '#ff0000', style: 'dotted' }, CKEDITOR.tools.style.parse.border( '#ff0000 dotted' ) );
+		},
+
+		'test style.parse.border with mixed color, style and width': function() {
+			objectAssert.areEqual( { width: '7.5em', color: '#ff0000', style: 'dotted' }, CKEDITOR.tools.style.parse.border( '#ff0000 dotted 7.5em' ) );
+		},
+
+		'test style.parse.border with style only': function() {
```
Comment (f1ames) [inline tests/core/tools/style.js]: Tests checking different color formats (`rgba`, `hsla`, color names) should be added (or you may modify existing tests so each contains different format).

File: plugins/table/plugin.js (hunk 1 above)
Comment (wojtekw92) [inline plugins/table/plugin.js]: this is temporary solution until #619 will be done. HTML border attribute is for solid border that's why we check only if its set to solid. It's the same behaviour as it was, just fixed for zero width issue.

Comment (f1ames) [inline plugins/table/plugin.js]: Fair enough.

File: core/tools.js [hunk 5]
```diff
@@ -1627,6 +1627,21 @@
...
+					'dashed',
+					'solid',
+					'double',
+					'groove',
+					'ridge',
+					'inset',
+					'outset'
+				],
+
+				_widthRegExp: /^(thin|medium|thick|[\+-]?\d+(\.?\d+|)[a-z%]+|0+(\.?0+|))$/,
```
Comment (f1ames) [inline core/tools.js]: Still this regexp has some issues:
image

You may try to group it somehow so it might be easier to match various scenarios (especially with 0).

File: core/tools.js [hunk 6]
```diff
@@ -1713,6 +1728,51 @@
 				},
 
 				/**
+				 * Parses the `border` CSS property shorthand format.
+				 * This CSS properyty doesn't support inherit. (https://www.w3.org/TR/css3-background/#the-border-shorthands)
```
Comment (f1ames) [inline core/tools.js]: Typo:

> This CSS proper~y~ty doesn't

File: tests/plugins/table/manual/border.md [hunk 7]
```diff
@@ -0,0 +1,12 @@
+@bender-tags: 4.7.1, bug, 566
```
Comment (f1ames) [inline tests/plugins/table/manual/border.md]: Please update tag to `4.7.2`.

File: tests/plugins/table/manual/border.md [hunk 8]
```diff
@@ -0,0 +1,12 @@
...
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea,toolbar,table,sourcearea,dialogadvtab
+
+
+
+1. Add table with Table button
```
Comment (f1ames) [inline tests/plugins/table/manual/border.md]: Missing `.` on sentence end.

File: core/tools.js (hunk 5 above)
Comment (wojtekw92) [inline core/tools.js]: Fixed but without engineering format support after discuss with Marek.

File: tests/plugins/table/table.js [hunk 9]
```diff
@@ -111,6 +111,39 @@
 
 			assert.isTrue( CKEDITOR.document.getBody().contains( editable ), 'Editable should not be removed' );
 			assert.areEqual( '', bot.editor.getData() );
+		},
+
+		// https://github.com/ckeditor/ckeditor-dev/issues/566
```
Comment (f1ames) [inline tests/plugins/table/table.js]: This should be `// (#566)`.

File: tests/plugins/table/table.js [hunk 10]
```diff
@@ -111,6 +111,39 @@
...
+							'<td></td>' +
+							'<td>x^x</td>' +
+						'</tr>' +
+					'</tbody>' +
+				'</table>' );
+
+			assert.isTrue( /border="0"/.test( bot.editor.getData() ), 'Border attribute shoulde be zero' );
+		},
+
+		'test html border attribute behaviour when CSS border is not  0': function() {
```
Comment (f1ames) [inline tests/plugins/table/table.js]: Please also add issue reference here.

File: core/tools.js [hunk 11]
```diff
@@ -1627,6 +1627,21 @@
...
+					'dashed',
+					'solid',
+					'double',
+					'groove',
+					'ridge',
+					'inset',
+					'outset'
+				],
+
+				_widthRegExp: /^(thin|medium|thick|[\+-]?\d+(\.?\d+|)[a-z%]+|[\+-]?0+(\.?0+|)|\.\d+[a-z%]+)$/,
```
Comment (f1ames) [inline core/tools.js]: RegExp works fine. I was just wondering about `(\.?\d+|)` and `(\.?0+|)`. Isn't it an equivalent to `(\.\d+)?` and `(\.0+)?` in this case? Which version do you find more readable?

File: core/tools.js [hunk 12]
```diff
@@ -1713,6 +1728,51 @@
...
+				 * @param {String} value The `border` property value.
+				 * @returns {Object}
+				 * @returns {String} return.width border-width attribute.
+				 * @returns {String} return.style border-style attribute.
+				 * @returns {String} return.color border-color attribute.
+				 * @member CKEDITOR.tools.style.parse
+				 */
+				border: function( value ) {
+					var ret = {};
+					var input = value.split( /\s+/ );
```
Comment (f1ames) [inline core/tools.js]: You can _merge_ values declarations here:

```
var ret = {},
    input = value.split( /\s+/ );
```

File: tests/plugins/table/table.js [hunk 13]
```diff
@@ -111,7 +111,40 @@
...
+							'<td></td>' +
+							'<td>x^x</td>' +
+						'</tr>' +
+					'</tbody>' +
+				'</table>' );
+
+			assert.isTrue( /border="0"/.test( bot.editor.getData() ), 'Border attribute should be zero' );
+		},
+
+		'test html border attribute behaviour when CSS border is not  0': function() {
```
Comment (f1ames) [inline tests/plugins/table/table.js]: Still missing issue reference here, please add it same way as in previous test.

File: plugins/table/plugin.js [hunk 14]
```diff
@@ -30,7 +30,22 @@ CKEDITOR.plugins.add( 'table', {
...
+							if ( element.styles.border ) {
+								parsedStyle = CKEDITOR.tools.style.parse.border( element.styles.border );
+							} else if ( CKEDITOR.env.ie && CKEDITOR.env.version === 8 ) {
+								var styleData = element.styles;
+								// Workaround for IE8 browser. IE8 after parsing CSS border param changes it for it
+								// basic comoponents(border-top...border-right). We have to check if those parameters exists and
+								// have the same value to get expected editor behavior. (#566)
+								if ( styleData[ 'border-left' ] && styleData[ 'border-left' ] === styleData[ 'border-right' ] &&
+										styleData[ 'border-right' ] === styleData[ 'border-top' ] &&
+										styleData[ 'border-top' ] === styleData[ 'border-bottom' ] ) {
```
Comment (f1ames) [inline plugins/table/plugin.js]: These two lines (42 and 43) are not properly indented, should be one `tab` less:
```
if ( styleData[ 'border-left' ] && styleData[ 'border-left' ] === styleData[ 'border-right' ] &&
    styleData[...
```

you may put one empty line before `if` body to increase readability.

**Comment by f1ames** [comment]
Rebased on latest `master` and cleanup history a little.
