### PR TITLE
Fix for: failing filetools related tests 

### LINKED ISSUE #3184: Failing filetools related tests
## Type of report

Failing test

image

Both tests are related to filetools plugin (uploadwidget uses filetools under the hood) so they are likely related.

Make sure to use the latest Edge browser.

## Other details

* Browser: Edge 18
* CKEditor version: 4.12.0

**Also fails on `4.11.4` version which means it is probably caused by Edge update (from version `17` to `18`)**.

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Fix failing tests

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## What is the proposed changelog entry for this pull request?

None

## What changes did you make?

Tests are failing due to upstream issue, so I ignored one of them, and forced polyfill which is used in IE for another test.

Closes #3184

### CODE REVIEW

**Comment by f1ames** [comment]
Rebased and retargeted onto latest `major`.

File: tests/plugins/uploadwidget/additionalrequestparameters.js [hunk 1]
```diff
@@ -112,10 +112,18 @@
 
 			File = window.File;
 
+			// Edge 18+ upstream issue breaks tests, workaround by forcing polyfill (#3184).
+			// developer.microsoft.com/en-us/microsoft-edge/platform/issues/22326784
+			if ( CKEDITOR.env.edge && CKEDITOR.env.version >= 18 ) {
+				assert.ignore();
+			}
+			var isEdge18 = CKEDITOR.env.edge && CKEDITOR.env.version >= 18;
```
Comment (f1ames) [inline tests/plugins/uploadwidget/additionalrequestparameters.js]: First you ignore the test then make Edge 18 detection to adjust test flow 🤔 Looks like one of these is a leftover?

Comment (engineering-this) [reply tests/plugins/uploadwidget/additionalrequestparameters.js]: Yup, probably leftover, it passes on Edge 18 now, so no need to ignore it.

**Comment by f1ames** [comment]
Rebased onto latest `major`.
