### PR TITLE
Fixed: Holding and releasing mouse button is not inserting autocomplete item

### LINKED ISSUE #2107: Holding and releasing mouse button is not inserting autocomplete item
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open `http://localhost:1030/tests/plugins/autocomplete/manual/viewposition`.
2. Focus first editor.
3. Type `@`.
4. Move mouse over the first dropdown item and press left mouse button. Release it after 2 seconds.

### Expected result

Item has been inserted into the editor.

### Actual result

Dropdown disappears and the item is not inserted into the editor.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.10.0
* Installed CKEditor plugins: autocomplete

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_contributing_code-section-tests),
[how to set the testing environment](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests) and
[how to create tests](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_tests-section-creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [X] Unit tests
- [X] Manual tests

## What changes did you make?

I've registered autocomplete items in focusManager, so focusing them wont trigger editor blur event which was cause for hiding dropdown. Note `tabindex` is required for items to be focusable.

Closes #2107.

### CODE REVIEW

**Comment by engineering-this** [comment]
I'm thinking if we should treat this as feature instead of just fix.

**Comment by engineering-this** [comment]
I will rebase it once `master` is merged with `major`.

File: plugins/autocomplete/plugin.js [hunk 1]
```diff
@@ -586,7 +587,7 @@
 		 * @readonly
 		 * @property {CKEDITOR.template}
 		 */
-		this.itemTemplate = new CKEDITOR.template( '<li data-id="{id}">{name}</li>' );
+		this.itemTemplate = new CKEDITOR.template( '<li data-id="{id}" tabindex="-1">{name}</li>' );
```
Comment (Comandeer) [inline plugins/autocomplete/plugin.js]: I'd rather add `[tabindex]` programatically, via `element.$.tabIndex = -1` in `addItem` method. Requiring user to remember to add this attribute to `itemTemplate` seems unnecessary.

**Comment by engineering-this** [comment]
After reconsidering this issue I decided to drop changes. I didn't delete commits, so it can be reverted.

For proper usage of autocomplete editor should remain focused all the time, so we can continue typing. Hence it shouldn't register anything in `focusManager`. Instead solution is to 
`event.preventDefault();` on `mousedown`, which solves the problem.

Now fix contain less code, quirks described above don't happen, and also this change solves #2126.
