### PR TITLE
Fixed emoji text matching with repeated symbols in a single line

### LINKED ISSUE #2394: Minimal character count for autocomplete is incorrect if preceded with an unfinished autocomplete match
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open any editor with Emoji plugin enabled.
2. Focus the editor.
3. Empty the contents (e.g. `ctrl/cmd+a`, `del`).
1. Type `:smiling_face`.
1. Press `esc` key to **cancel** completion, so it doesn't get replaced by a emoji.
1. Press `space`.
1. Type `:smi`.

### Expected result

Dropdown with emoji appears.

### Actual result

No dropdown appears.

## Other details

Interestingly if you continue the typing till you have `:smiling_face_` (so that it is longer than the first token) the autocomplete appears.

This issue is very, very awkward. At first I thought that matching doesn't work at all, but then it seemed to me that it works, but minimal charcount is considered based on preceding match.

I presume that the issues is in autocomplete plugin rather than emoji. 

Looks like it's a regression in **4.10.1** as I can't reproduce it with 4.10.0. I guess that it got introduced with #2195.

* Browser: Any
* OS: Any
* CKEditor version: 4.10.1

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

Emoji symbol was incorrectly matched when tested text have duplicated symbols.

Closes #2394

### CODE REVIEW

File: tests/plugins/emoji/basic.js [hunk 1]
```diff
@@ -31,6 +31,12 @@
 
 	var stub = null;
 
+	// Disable autocomplete throttling so the tests can be run synchronously.
+	var throttle = CKEDITOR.tools.buffers.throttle;
```
Comment (mlewand) [inline tests/plugins/emoji/basic.js]: If possible try to merge subsequent var statements.

File: tests/plugins/emoji/basic.js [hunk 2]
```diff
@@ -177,16 +167,21 @@
...
+		// (#2394)
+		'test emoji correctly matches repeated keywords': function( editor, bot ) {
+			emojiTools.runAfterInstanceReady( editor, bot, function( editor, bot ) {
+				var autocomplete = editor._.emoji.autocomplete;
 
-				editable.fire( 'keyup', new CKEDITOR.dom.event( {} ) );
-				wait();
+				bot.setHtmlWithSelection( '<p>foo :collision :collision^</p>' );
+				editor.editable().fire( 'keyup', new CKEDITOR.dom.event( {} ) );
+				assert.areSame( ':collision', autocomplete.model.query, 'Model keeps wrong querry.' );
```
Comment (mlewand) [inline tests/plugins/emoji/basic.js]: There should be no dots at the end of assert msg. I can see that you might have take it from other asserts in this suite.

What's interesting is that `objectAssert`s have correct form 🙂

File: tests/plugins/emoji/manual/repeated.html [hunk 3]
```diff
@@ -0,0 +1,10 @@
+<h2>Classic editor</h2>
+<div id="classic"></div>
+<h2>Inline editor</h2>
+<div id="inline" contenteditable="true">
```
Comment (mlewand) [inline tests/plugins/emoji/manual/repeated.html]: Just a detail, but since you're closing all of the tags in a single line, it would be nice to close this one as well.

File: tests/plugins/emoji/basic.js (hunk 2 above)
Comment (mlewand) [reply tests/plugins/emoji/basic.js]: typo querry -> query
