### PR TITLE
Fix for getCommandKeystroke

### LINKED ISSUE #523: Cannot obtain commandKeystroke from the editor
## Are you reporting a feature or a bug?
BUG

## Provide detailed reproduction steps (if any)

1. Open browser console.
1. Execute: `CKEDITOR.instances.editor.getCommand( 'selectAll' )`
1. It should return command. We have sure that command exists.
1. Execute `CKEDITOR.instances.editor.keystrokeHandler.keystrokes`
1. It should return an array of `keystroke`'s. So we have sure that `selectAll` exists and is registered by editor
1. Execute `CKEDITOR.instances.editor.getCommandKeystroke( CKEDITOR.instances.editor.getCommand('selectAll') )`
1. It returns `null`, for command which has returned assigned keystroke.

### Expected result
possibility to obtain `commandKeystroke` based on command name.
 
### Actual result
There is no command

## Other details
* CKEditor version: 4.7.0
* Installed CKEditor plugins: full

### PR DESCRIPTION
**Pull request by msamsel**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

unit tests only
### This PR contains

- [x] Unit tests
- [ ] Manual tests

## What changes did you make?
- add new helper `CKEDITOR.tools.object.findKey()`
- fix `getCommandKeystroke` to return proper keystrokes

Close #523

### CODE REVIEW

File: core/tools.js [hunk 1]
```diff
@@ -1844,6 +1844,39 @@
...
+		 *
+		 * @property {CKEDITOR.tools.object}
+		 * @member CKEDITOR.tools
+		 */
+		object: {
+			/**
+			 * Return a first key from `obj` which has given value. If key cannot be find, `null` is returned.
+			 *
+			 * @param {Object} obj Object which key is looked for.
+			 * @param {Mixed} value Object's vlaue which key is looked for
```
Comment (mlewand) [inline core/tools.js]: Missing dot, typo in "vlaue". Also I think it would be more readable to put it like "Object's value to be looked for.".

File: core/tools.js [hunk 2]
```diff
@@ -1844,6 +1844,39 @@
...
+			 * @returns {String/null} Key string
```
Comment (mlewand) [inline core/tools.js]: How about "Matched key or `null` if not found."?

File: core/tools.js [hunk 3]
```diff
@@ -1844,6 +1844,39 @@
...
+
+		/**
+		 * A set of object helpers.
+		 *
+		 * @property {CKEDITOR.tools.object}
+		 * @member CKEDITOR.tools
+		 */
+		object: {
+			/**
+			 * Return a first key from `obj` which has given value. If key cannot be find, `null` is returned.
```
Comment (mlewand) [inline core/tools.js]: "If key cannot be find, `null` is returned." that part should be explained in `@returns` tag.

File: tests/core/editor/keystrokehandler.js [hunk 4]
```diff
@@ -94,5 +97,26 @@ bender.test(
 	'test editor#getCommandKeystroke with empty name': function() {
 		var editor = this.editor;
 		assert.isNull( editor.getCommandKeystroke( '' ), 'Returned keystroke.' );
+	},
+
+	// #523
+	'test keystroke with capitall letters': function() {
```
Comment (Comandeer) [inline tests/core/editor/keystrokehandler.js]: Small typo. Should be `capital letters`.

File: core/tools.js [hunk 5]
```diff
@@ -1844,6 +1844,39 @@
...
+			/**
+			 * Return a first key from `obj` which has given `value`.
+			 *
+			 * @param {Object} obj Object which `key` is looked for.
+			 * @param {Mixed} value Object's `value` to be looked for.
+			 * @returns {String/null} Matched `key` or `null` if not found.
+			 * @member CKEDITOR.tools.object
+			 */
+
+			findKey: function( obj, value ) {
```
Comment (Comandeer) [inline core/tools.js]: It'd be nice to add some basic unit tests. You can look how `tests/core/tools/array.js` is done and do something similiar in `tests/core/tools/object.js`.
