### PR TITLE
[#704] Fix broken widget after using Ctrl+Z in Edge

### LINKED ISSUE #704: Broken content in article editor after using shortcut CTRL+Z
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open Edge browser.
2. Go to http://ckeditor.com/ and choose `Article Editor`.
3. Put caret at the end of the text.
4. Press `Enter`.
5. Use `CTRL+Z` shortcut to undo.

### Expected result

The layout looks the same as before use `CTRL+Z` shortcut.

### Actual result

The layout is broken.

## Other details
* Support ticket number: 32334
* Browser: Microsoft Edge 38.14393.1066.0, Microsoft EdgeHTML 14.14393
* OS: Windows 10

If you use the F12 developer tools to change the User Agent String to Chrome the site works as expected.

Here is additional information about the Edge UA String: https://msdn.microsoft.com/library/hh869301(v=vs.85).aspx

### PR DESCRIPTION
**Pull request by msamsel**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

yes

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

* Modify condition which remove unnecessary `div` in Edge.
* Modify condition to work only in Edge up to 14.xxx. (Edge 15 doesn't add `div`).
* Modify tests to respect new condition related to Edge version.

Close #704

### CODE REVIEW

File: plugins/wysiwygarea/plugin.js [hunk 1]
```diff
@@ -297,7 +297,7 @@
 				var elements = doc.getElementsByTag( tagName );
 				if ( lockRetain ) {
 					if ( elements.count() == 1 && !elements.getItem( 0 ).getCustomData( 'retain' ) &&
-						!elements.getItem( 0 ).hasAttribute( 'data-cke-temp' ) ) {
+						CKEDITOR.tools.isEmpty( elements.getItem( 0 ).getAttributes() ) ) {
```
[the remark this answers is not in the document]
Comment (msamsel) [reply plugins/wysiwygarea/plugin.js]: Entire function `removeSuperfluousElement` was design to remove additional `div` which appear in Edge, when all text is removed from editor. This div never had any attribute. Unfortunately author hadn't predict that not only those extra `divs` might appear, but also widgets might be construct based on `div`. And in case of `undo` command entire widget might be redraw so we lost `retain` customData attached to `div`.
This change detects more carefully only those extra divs from Edge, so it becomes more specific. Now divs connected to widgets won't be removed.

File: tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.html [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+	Combine the flour, sugar and cocoa powder in a medium bowl. In another small bowl, whisk together the butter and eggs. Stir the two mixtures until just combined.
+	Bake the brownies for 25 to 35 minutes. Remove from the oven and let it cool for 5 minutes.
+	</p>
+</textarea>
+<pre id="output" style="background-color: lightgreen;"></pre>
+<script>
+	var editor = CKEDITOR.replace( 'editor1', {
+		height: '600px'
+	} );
+	setInterval( function() {
```
[the remark this answers is not in the document]
Comment (msamsel) [reply tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.html]: Unfortunately `change` event is not working as it should. :( It's execute before `keyup` listener removes div from `wysiwygarea`. I've used `keyup` listener instead.

File: tests/plugins/widget/integration/wysiwygarea/superflousdoesntremovedivwrapper.js [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+				var editor = bot.editor;
+
+				editor.editable().fire( 'keydown', new CKEDITOR.dom.event( {
+					keyCode: 90,
+					ctrlKey: true,
+					shiftKey: false
+				} ) );
+
+				var snap = editor.getSnapshot();
+				editor.loadSnapshot( snap );
```
[the remark this answers is not in the document]
Comment (msamsel) [reply tests/plugins/widget/integration/wysiwygarea/superflousdoesntremovedivwrapper.js]: Yes.
`keydown` and `keyup` don't trigger undo command, which triggers re-creating widget (there even is no history to revert it). 
So this simulation works as follows:
1. Simulate `keydown` to register listeners on `div` by superflous function.
2. Reload snapshot, to simulate <kbd>Ctrl</kbd>+<kbd>Z</kbd>, when previous snapshot is restored.
3. Reloading snapshot automatically triggers re-creating widget. Here will be destroyed wrapping div for widget, and `retain` attribute will be lost (as it happens in Edge).
4. Simulate `keyup` to execute proper listener from superflous function.

Re-loading snapshot might be replaced with some kind of triggering undo event, but it would require much more work. First to make some history, and then revert it. So I extract only important part from entire undo process, which is reloading snapshot, what cause the issue in case of using shortcut. This allows on proper simulation behaviour on Edge and proper fail of test in case of Edge environment without bug fix.

File: plugins/wysiwygarea/plugin.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (f1ames) [reply plugins/wysiwygarea/plugin.js]: Makes sense 👍

File: tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.md [hunk 4]
```diff
@@ -0,0 +1,11 @@
+@bender-ui: collapsed
+@bender-tags: bug, 4.7.2, 704
+@bender-ckeditor-plugins: image2, wysiwygarea, undo, sourcearea
+
+----
+1. Put caret in the text on the right and type some text.
+1. Use `Ctrl + Z` or `Cmd + Z` shortcut to make undo few times.
+
+**Expected:** Text returns to previous form. Below editor will be written `div` on green background.
```
Comment (f1ames) [inline tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.md]: Maybe:

> Text returns to previous form. Below **the** editor, you should see `div` on green background.

File: tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.md [hunk 5]
```diff
@@ -0,0 +1,11 @@
...
+
+**Unexpected:** Text moves below the image. Below editor will be written `figure` instead of `div`.
```
Comment (f1ames) [inline tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.md]: And:

> Text moves below the image. Below editor, it will be written `figure` instead of `div` on the green background.

File: tests/plugins/widget/integration/wysiwygarea/superflousdoesntremovedivwrapper.js [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+
+	bender.editor = {
+		config: {
+			allowedContent: true
+		}
+	};
+
+	bender.test( {
+		// #704
+		'test keeping widget wrapper in editor when superflous elemnts are checked': function() {
```
Comment (f1ames) [inline tests/plugins/widget/integration/wysiwygarea/superflousdoesntremovedivwrapper.js]: Typo:

> test keeping widget wrapper in editor when superfl**u**ous elem**e**nts are checked

File: tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.html [hunk 7]
```diff
@@ -0,0 +1,22 @@
+<textarea id="editor1" name="editor1">
```
Comment (f1ames) [inline tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.html]: This test fails on IE8 due to `addEventListener`, if it should be run only for Edge add a proper `bender.ignore` or fix attaching listener if it should be run also for IE8.

Comment (msamsel) [reply tests/plugins/widget/integration/wysiwygarea/manual/preventofremovingdiv.html]: I added both things. I know it wasn't necessary, but this not harm anything. ;)

**Comment by msamsel** [comment]
I've made fixes and rebase branch to major. Also switch target branch on github to major.
