### PR TITLE
Fix for: Resize handler was visible after entering read-only mode manually

### LINKED ISSUE #2816: Resize handler is visible in read-only mode
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/image2.html
2. Open browser console.
3. Paste and execute following code in console:
	```javascript
	CKEDITOR.instances.editor1.setReadOnly( true );
	```
4. Try to resize image in the first editor.

### Expected result

* Image can't be resized.
* Resize handler is not visible.

### Actual result

* Image can be resized.
* Resize handler is visible.

## Other details

* Installed CKEditor plugins: image2

There was #719, but it fixed issue only for editors loaded in read-only mode. As we're introducing hiding of drag handler in #865, it'd be nice to provide the same change also for resize handler.

### LINKED ISSUE #2874: Resize handler is not created for images in read-only mode
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create read-only instance of editor containing image
2. Open webpage
3. Paste and execute following code in console:
  ```js
  CKEDITOR.instances.editor1.setReadOnly( false );
  ```
4. Try to resize image in the first editor.

### Expected result

* Resize handler is visible
* Image can be resized

### Actual result

* Resize handler is not visible
* Image can not be resized

## Other details

* Installed CKEditor plugins: image2

#719 made resize handler disabled if editor is created in read-only mode. However it is not initialised at all, so after manually leaving read-only mode resize handler still does not show up.
Note that this is an issue only for images loaded with editor. If you add a new image afterwards (i.e. after leaving read-only mode), the problem does not exist.

### PR DESCRIPTION
**Pull request by Dumluregn**
## What is the purpose of this pull request?

Bugfix

## Does your PR contain necessary tests?

Yes

### This PR contains

- [x] Manual test
- [x] Unit test

## What changes did you make?

Resize handler does not show up on hover if content is not editable. I added one css rule for that.
Also unit test logic has been changed - now it checks if resize handler is properly initialized in all scenarios.

Closes #2816.
Closes #2874.

### CODE REVIEW

**Comment by jacekbogdanski** [comment]
Now I see that you already reported an issue with the missing resizer for a read-only editor: https://github.com/ckeditor/ckeditor-dev/issues/2874 so it makes sense to fix both issues at once with this PR, thus probably your style change won't be needed anymore if resizer will be correctly handled.

File: tests/plugins/image2/resizerwithreadonly.js [hunk 1]
```diff
@@ -42,13 +42,37 @@
 					listener.removeListener();
 
 					resume( function() {
-						assert.areSame( 2, editor.editable().getElementsByTag( 'span' ).$.length );
+						assert.areSame( 3, editor.editable().getElementsByTag( 'span' ).$.length );
```
Comment (jacekbogdanski) [inline tests/plugins/image2/resizerwithreadonly.js]: Let's be more precise here and check if widget really contains resizer element. Also, it would be nice to specify image widget element, so we are sure that the resizer is a part of the widget. Small code example which could lead you on the correct track:

```javascript
var resizer = editor.editable().findOne( '.cke_widget_image .cke_image_resizer' );
assert.isTrue( Boolean( resizer ), 'Resizer should be enabled'  );
```

Improve also the rest of the tests in this file with recommended changes.

File: tests/plugins/image2/resizerwithreadonly.js [hunk 2]
```diff
@@ -5,7 +5,7 @@
 	'use strict';
 
 	bender.test( {
-		// #719
+		// #719, #2816, #2874
 		'test readOnly set to false': function() {
```
Comment (jacekbogdanski) [inline tests/plugins/image2/resizerwithreadonly.js]: We can now rename this test into `test resizer setup`.

File: CHANGES.md [hunk 3]
```diff
@@ -3,6 +3,10 @@
 
 ## CKEditor 4.11.4
 
+Fixed Issues:
+
+* [#2816](https://github.com/ckeditor/ckeditor-dev/issues/2816), [#2874](https://github.com/ckeditor/ckeditor-dev/issues/2874): Fixed: [Enhanced Image](https://ckeditor.com/cke4/addon/image2) resize handler is visible after manually setting [Read-Only Mode](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_readonly.html).
```
[the remark this answers is not in the document]
Comment (Dumluregn) [reply CHANGES.md]: There are two issues so comma is ok, but according to your point I will split this entry into two and describe both properly for better clarity.

File: CHANGES.md [hunk 4]
```diff
@@ -3,6 +3,11 @@
 
 ## CKEditor 4.11.4
 
+Fixed Issues:
+
+* [#2816](https://github.com/ckeditor/ckeditor-dev/issues/2816): Fixed: [Enhanced Image](https://ckeditor.com/cke4/addon/image2) resize handler is not created in [Read-Only Mode](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_readonly.html) editor.
+* [#2874](https://github.com/ckeditor/ckeditor-dev/issues/2874): Fixed: [Enhanced Image](https://ckeditor.com/cke4/addon/image2) resize handler is visible after entering [Read-Only Mode](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_readonly.html) using console command.
```
Comment (jacekbogdanski) [inline CHANGES.md]: A small suggestion - don't try to predict the usage of the API if the issue is not based on some environment variables (it's something you already tried with `manually setting Read-Only mode`). Will it work correctly if you write in your app source code `editor.setReadOnly( true )` instead of using it in the console?

Rephrase this sentence into 

> [#2874](https://github.com/ckeditor/ckeditor-dev/issues/2874): Fixed: [Enhanced Image](https://ckeditor.com/cke4/addon/image2) resize handler is visible after entering [Read-Only Mode](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_readonly.html).

File: tests/plugins/image2/resizerwithreadonly.js [hunk 5]
```diff
@@ -42,7 +41,31 @@
 					listener.removeListener();
 
 					resume( function() {
```
Comment (jacekbogdanski) [inline tests/plugins/image2/resizerwithreadonly.js]: Your tests may be a bit simplified by reusing `editor.setData` the second argument which is a callback called when data is ready (basically the same logic you proposing although hidden by nice API). More info at https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-setData

```javascript
editor.setData( '<img src="_assets/foo.png" alt="" />', function() {
	resume( function() {
		var resizer = editor.editable().findOne( '.cke_widget_image .cke_image_resizer' );
		assert.isTrue( Boolean( resizer ), 'Resizer should be enabled'  );
	} );
} );

wait();
```

File: tests/plugins/image2/resizerwithreadonly.js [hunk 6]
```diff
@@ -5,48 +5,61 @@
...
-					dialog.setValueOf( 'info', 'src', '_assets/foo.png' );
-					dialog.getButton( 'ok' ).click();
-
-					assert.sameData(
-						'cke_image_resizer',
-						editor.editable().getElementsByTag( 'span' ).$[ 2 ].outerHTML.match( /(cke_image_resizer)/g )[ 0 ]
-					);
+				editor.setData( '<img src="_assets/foo.png" alt="" />', function() {
+					resume( function() {
+						editor.setReadOnly( true );
```
Comment (jacekbogdanski) [inline tests/plugins/image2/resizerwithreadonly.js]: This test despite refactoring should still follow the same logic, which means `editor.setReadOnly( true )` is redundant here / makes the test identical like `test readOnly set to true after initialization`.

**Comment by f1ames** [comment]
Rebased on latest `master`.

File: tests/plugins/image2/manual/resizerwithreadonly.md [hunk 7]
```diff
@@ -1,5 +1,19 @@
...
+@bender-tags: 4.7.3, 4.11.4, bug, 719, 2816, 2874
 @bender-ui: collapsed
 @bender-ckeditor-plugins: wysiwygarea, toolbar, image2
 
-Only **first** editor should have enabled mouse resizer on image.
+## Classic Editor
+
+1. Focus the image.
+
+**Expected:** The image has enabled mouse resizer.
```
Comment (f1ames) [inline tests/plugins/image2/manual/resizerwithreadonly.md]:
```suggestion
**Expected:** The image resize handler is visible.
```

File: tests/plugins/image2/manual/resizerwithreadonly.md [hunk 8]
```diff
@@ -1,5 +1,19 @@
...
+
+## ReadOnly Editor
+
+1. Focus the image.
+
+**Expected:** The image doesn't have enabled mouse resizer.
```
Comment (f1ames) [inline tests/plugins/image2/manual/resizerwithreadonly.md]:
```suggestion
**Expected:** The image resize handler is not visible.
```

File: tests/plugins/image2/manual/resizerwithreadonly.md [hunk 9]
```diff
@@ -1,5 +1,19 @@
...
+
+2. Click `Toggle read-only mode` multiple times focusing image every time after button click.
+
+**Expected:** The image mouse resizer is enabled and disabled depending on the read-only mode state.
```
Comment (f1ames) [inline tests/plugins/image2/manual/resizerwithreadonly.md]:
```suggestion
**Expected:** The image resize handler is enabled/disabled depending on the read-only mode state.
```

**Comment by Dumluregn** [comment]
Fix works on Safari Version 12.0.3 (14606.4.5):
read-only

**Comment by Dumluregn** [comment]
Thanks for your comment, of course I will implement tests the way you suggested.

File: tests/plugins/image2/resizerwithreadonly.js [hunk 10]
```diff
@@ -1,54 +1,75 @@
...
+		bender.editorBot.create( profile, function( bot ) {
+			var editor = bot.editor;
+
+			editor.setData( '<img src="_assets/foo.png" alt="" />', function() {
+				resume( function() {
+					if ( readOnly ) {
+						editor.setReadOnly( readOnly );
+					}
+					var resizer = editor.editable().findOne( '.cke_widget_image .cke_image_resizer' );
+					assert.isTrue( Boolean( resizer ), 'Resizer should be created'  );
```
Comment (f1ames) [inline tests/plugins/image2/resizerwithreadonly.js]: Better fit to check if element exists is to use `assert.isNotNull`. Also since `resizer` is used only once maybe it could be a one-liner:

```js
assert.isNotNull( editor.editable().findOne( '.cke_widget_image .cke_image_resizer' ), 'Resizer should be created' );
```

**Comment by f1ames** [comment]
Rebased on the latest `master`.
