### PR TITLE
Fix for: image2 throws an exception when empty figure with class 'image' is upcasted

### LINKED ISSUE #2506: image2: throws an exception if set a content with an empty figure tag
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1.  Set extraPlugin as `config.extraPlugins = 'image2'`;
2.  Set a value for ckeditor as  `<figure class="image"></figure>`

image2 plugin throws an exception if ckeditor's content contains empty "figure" tag (or if a "figure" does not contains nor "img" nor "a" tag). 

```
<div id="editor">
    <figure class="image"></figure>
</div>

```

image2  expects that "figure" must always contains "img" tag or "a" tag that contains "img".
`image = el.getFirst( 'img' ) || el.getFirst( 'a' ).getFirst( 'img' );`
The issue can be reloved by adding additional checking:
`image = el.getFirst( 'img' ) || (el.getFirst( 'a' ) && el.getFirst( 'a' ).getFirst( 'img' ));`

### Expected result

Exception should not be thrown.

### Actual result

`Uncaught TypeError: Cannot read property 'getFirst' of null`  exception is being thrown.

## Other details

* Browser: Google Chrome 70, FireFox 62
* OS: Windows 10
* CKEditor version: ckeditor_4.10.1
* Installed CKEditor plugins: image2

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Bug Fix

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## What changes did you make?

Added an extra check in upcasting method, so it won't throw type error.

Closes #2506

### CODE REVIEW

File: tests/plugins/image2/upcast.js [hunk 1]
```diff
@@ -37,7 +37,7 @@
 				name: 'enterP',
 				data: '<p style="text-align:center">' +
 					'<img id="w1" src="_assets/foo.png" alt="foo" />' +
-				'</p>'
+					'</p>'
```
Comment (engineering-this) [inline tests/plugins/image2/upcast.js]: Just hit that autoformatting keystrong, although that's correct indentation so I'm keeping that.

Comment (Comandeer) [reply tests/plugins/image2/upcast.js]: Actually it's not correct, as nested `img` tag is on the same level as `p` now.

File: plugins/image2/plugin.js [hunk 2]
```diff
@@ -942,7 +942,8 @@
 
 			// No center wrapper has been found.
 			else if ( name == 'figure' && el.hasClass( captionedClass ) ) {
-				image = el.getFirst( 'img' ) || el.getFirst( 'a' ).getFirst( 'img' );
+				var anchor = el.getFirst( 'a' );
+				image = el.getFirst( 'img' ) || ( anchor && anchor.getFirst( 'img' ) );
```
Comment (Comandeer) [inline plugins/image2/plugin.js]: I wonder if [`find`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlParser_element.html#method-find) wouldn't be more readable here:

```javascript
image = el.find( function( child ) {
	return child.name === 'img' &&
		CKEDITOR.tools.array.indexOf( [ 'figure', 'a' ], child.parent.name ) !== -1;
}, true )[ 0 ];
```

The issue I have with [`getFirst`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_htmlParser_element.html#method-getFirst) is the fact that it works in totally counter-intuitive way, changing behaviour when parameter is passed (bold's mine):

> Gets this element's first child. If condition is given, this method returns the first child **which satisfies that condition**.

Maybe the version with `find` is more verbose, yet also more explicit and easier to understand – without the need to consult the docs.

File: tests/plugins/image2/manual/upcast.md [hunk 3]
```diff
@@ -0,0 +1,17 @@
+@bender-tags: 4.11.2, bug, 2506
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea, toolbar, image2, sourcearea
+
+1. Open developer console.
```
Comment (Comandeer) [inline tests/plugins/image2/manual/upcast.md]: Probably testing procedure could be simplified, e.g. by adding two buttons, which will be inserting empty `figure` and `figure > a` elements.

File: tests/plugins/image2/upcast.js (hunk 1 above)
Comment (engineering-this) [reply tests/plugins/image2/upcast.js]: You are right. It's not correct as html markup it would be for regular string, however original one wasn't correct either, as `'</p>'` shouldn't be on same level as `data` property.
