### PR TITLE
Fixed failing tests on vertical screens

### LINKED ISSUE #2347: Tests absoluterectposition and  positioning.inline failing on high vertical resolution
## Type of report

Bug (Failing test)

## Provide detailed reproduction steps (if any)

Tests:

* http://tests.ckeditor.test:1030/tests/core/tools/absoluterectposition
* http://tests.ckeditor.test:1030/tests/plugins/balloonpanel/positioning.inline

Are failing when ran on a vertically oriented display.

The workaround is to make the browser window smaller.

## Other details

* Browser: Any

### PR DESCRIPTION
**Pull request by engineering-this**
## What is the purpose of this pull request?

Failing tests

## Does your PR contain necessary tests?

All patches which change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## What changes did you make?

`tests/core/tools/absoluterectposition`
- Firefox returned float numbers, as they were differing by less than one pixel I've rounded them
- Space filler had 2000px height, as it wasn't enough to make scrollbars visible in vertical monitors I've increased it's size to 5000px.

`tests/plugins/balloonpanel/positioning.inline`
- Firefox returned float numbers, as they were differing by less than one pixel I've rounded them
Closes #2347

### CODE REVIEW

File: tests/plugins/balloonpanel/_helpers/tools.js [hunk 1]
```diff
@@ -25,10 +25,16 @@ var balloonTestsTools = {
 		}
 	},
 
-	assertMoveTo: function( moveMethod, expectedX, expectedY, maxX, maxY ) {
+	assertMoveTo: function( moveMethod, expectedX, expectedY, maxX, maxY, shouldRound ) {
```
Comment (Comandeer) [inline tests/plugins/balloonpanel/_helpers/tools.js]: This method became highly unreadable. It'd be better to refactor it to use `options` object instead of 6 independent parameters.

Additionally some API docs would be nice.

**Comment by engineering-this** [comment]
`tests/core/tools/absoluterectposition`
Rewrote with mocked methods, that returns various outputs depending on browser, screen resolution, and zoom. Now everything is repeatable in any environment.

`tests/plugins/balloonpanel/positioning.inline`
Increased size of body.
